# ~/.config/alacritty/alacritty.toml

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 12.0

[cursor]
style.shape = "Block"
style.blinking = "Never"

[window]
decorations = "Full"
padding.x = 8
padding.y = 8
startup_mode = "Windowed"

