# ~/.config/alacritty/alacritty.toml
# Default Alacritty configuration

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 12.0

[cursor]
style.shape = "Block"
style.blinking = "Never"

[window]
decorations = "None"
padding.x = 25
padding.y = 25
startup_mode = "Windowed"
opacity = 1.0

[scrolling]
history = 1500
multiplier = 10